fix: listen for keydown to make event for action menu dropdown toggle…
Neovici/cosmoz-bottom-bar pull request #141
Opened 2024-03-11 15:52 UTC by micaelagoffe

Listen for keydown (shift+a) to dispatch an event for action menu dropdown toggle + change vscode settings

2024-03-13 12:19 UTC, megheaiulian requested changes

2024-03-13 12:19 UTC, megheaiulian commented on cosmoz-bottom-bar.js
> +		window.addEventListener('keydown', (event) => {
We can't add a event listener and not clean it up at some point ....

2024-03-13 12:20 UTC, megheaiulian commented on cosmoz-bottom-bar.js
> +		window.addEventListener('keydown', (event) => {
https://polymer-library.polymer-project.org/3.0/docs/devguide/events#listener-on-outside-elements

2024-03-13 12:25 UTC, cristinecula requested changes

2024-03-13 12:25 UTC, cristinecula commented on cosmoz-bottom-bar.js
> +	}
I don't think that this code needs to be here. First of all the name `toggle-action-list` does not make sense in the context of this component. What action list?
Second: all it does is dispatch an event when Shift+A is pressed. As the code stands, there is no reason for this round-aboutness. You can easily move the code to the app and skip the need for a `toggle-action-list` event. Maybe I am missing something. How does this help you?

2024-03-14 12:56 UTC, cristinecula approved these changes

2024-03-14 12:56 UTC, merged