Convert to pionjs
Neovici/cosmoz-bottom-bar pull request #144
Opened 2024-04-12 08:53 UTC by florianstancioiu

Convert the `cosmoz-bottom-bar` component to pionjs

2024-04-24 05:28 UTC, megheaiulian requested changes
We should set the css as a constructed stylesheet using the `styleSheets` option in `component`. 
Examples can be be found in frontend. `css` and `sheet` can be imported from cosmoz-utils.

2024-04-24 05:28 UTC, megheaiulian commented on src/cosmoz-bottom-bar-next.js
> +		// return this._setHasMenuItems(false); // TODO: Ask about this line
```suggestion
		return host.toggleAttribute('has-menu-items', false);
```

2024-04-24 05:28 UTC, megheaiulian commented on src/cosmoz-bottom-bar-next.js
> +	//this._setHasActions(hasActions); // TODO: Ask about this line
I think we can remove this for now.

2024-04-24 05:32 UTC, megheaiulian requested changes
We also need to adjust exports:

@neovici/cosmoz-bottom-bar should import previous version as before.
@neovici/cosmoz-bottom-bar/next should import your new version.

Please make sure you also test this in frontend with npm link.

2024-04-25 05:23 UTC, megheaiulian approved these changes

2024-04-25 06:12 UTC, cristinecula approved these changes
Very clean work, I love it!

I noticed that it does not react to `maxToolbarItems` changes, but that's not very important right now.

2024-04-25 06:16 UTC, merged